### ISSUE TITLE
TypeError: 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by azze-r** [dangillet/Pythoria#1]
Hey,
I want to try this game, after git clone https://github.com/dangillet/Pythoria, and after adding all library (you need requirements.txt to make it easy..., because we have to download one after one), i finally try to execute the main a windows is opened, and juste after it's closed :O , i don't know why, and i have this message : 

```
python2 pythoria/main.py 
Traceback (most recent call last):
  File "pythoria/main.py", line 57, in <module>
    main()
  File "pythoria/main.py", line 23, in main
    level1 = Dungeon.load_from_file('map/bigmap.txt')
  File "/home/boblinux/projets/Pythoria/pythoria/dungeon.py", line 65, in load_from_file
    with open(filename, 'r', encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function
```

For more informations : 

```
python2 --version
Python 2.7.10

uname -a
Linux bobpc 3.18.21-1-MANJARO #1 SMP PREEMPT Wed Sep 2 22:54:43 UTC 2015 x86_64 GNU/Linux
```

Maybe, you can see here : 
http://stackoverflow.com/questions/25049962/is-encoding-is-an-invalid-keyword-error-inevitable-in-python-2-x

**Comment by dangillet** [comment]
Hi,

Thanks for your interest in this project. Unfortunately it is unmaintained. It's purpose was to learn with 2 more people some typical patterns for _larger_ projects. 

I do agree that a requirements.txt should have been provided. Actually even a setup.py. But again, the purpose was just to learn as a group and then the project was abandoned. 

Although not documented, the code is for Python 3, not 2. If you are interested You could try to make it Python 2 compatible. It should not be too complicated. 

Daniel.

**Comment by azze-r** [comment]
I don't know if it is a good idea to make it compatible with python2, there is no reason to go back to python2, i will try it in python3, but i had some problems with librarys, i'll try it and print the result here. I have been interested of the project because i know @Buffalo974 (python community) **

Thanks for responsding.

**Comment by azze-r** [comment]
Ok, resolved, to begin work, you just have python3 pip on installed.

and so you do(in archlinux like distros) :

```
pip3 install pygame
pip3 install pygcurse 
python3 main.py
```

and it works !
